---

- hosts: all

# Ansible tasks #
  tasks:

# Gather Ansible Facts About Host #
    - name: Gather Ansible Facts About Host
      setup:
        gather_subset:
          - all
    - debug: 
        msg: "{{ ansible_facts }}"
